version: '2'
services:
  proxy_tower:
    build: .
    image: "worldwonderer/proxy_tower"
    environment:
      - redis_host=redis
    ports:
      - "8893:8893"
    links:
      - redis
  redis:
    image: "redis:latest"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
