version: '2'
services:
  proxy_tower:
    build: .
    image: "worldwonderer/proxy_tower"
    environment:
      - redis_host=redis
    ports:
      - "8893:8893"
    networks:
      - app
  redis:
    image: "redis:latest"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    networks:
      - app
  nginx:
    image: "nginx:latest"
    ports:
      - "8894:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./dashboard/:/usr/share/nginx/dashboard"
networks:
  app:
